### ISSUE TITLE
Header height is not preserved after screen rotation

### ISSUE THREAD

**Issue by h6ah4i** [noties/Scrollable#1]
Hi. I noticed that the sample app does not preserve the header view height after screen rotation.

P.S. Thanks for the superb library, this is what I am just looking for! I am willing to contribute this library :)

**Comment by noties** [comment]
HI!
Thanks for your response. To save the scroll state you just have to save it yourself, unfortunately, just like any widget (ListView, RecyclerView, ScrollView, etc.). I added to the sample project `howto`. In the case of ScrollableLayout you have to ask for getScrollY() onSaveInstanceState and manually call ScrollableLayout.scrollTo(x, y);.
But It's definitely the feature that should be in the library. 
I might also notice, that ScrollableLayout should not save the maxScrollY & friction properties, because they could be easily dependable on orientation (thus might have different values). So, these values should be set on view creation (just like listeners, etc.)

**Comment by h6ah4i** [comment]
Hi.

> To save the scroll state you just have to save it yourself, unfortunately, just like any widget (ListView, RecyclerView, ScrollView, etc.).

Really? I believe those Android framework widgets save and restore their scroll state automatically and basically users are no need to implement that manually.

> I might also notice, that ScrollableLayout should not save the maxScrollY & friction properties, because they could be easily dependable on orientation (thus might have different values). So, these values should be set on view creation (just like listeners, etc.)

Thanks for pointing me out. You are right.

**Comment by noties** [comment]
> Really? I believe those Android framework widgets save and restore their scroll state automatically and basically users are no need to implement that manually.

Well, it depends. In case of Fragment it might be the case, but anywhere else it's not. One have to manually call onSaveInstanceState() and then onRestoreInstanceState().

**Comment by noties** [comment]
implemented in 606dad7f11b7ad30c5c8891438f40c95d4e733fb
