### ISSUE TITLE
Change viewpager item size dynamically with listview scroll

### ISSUE THREAD

**Issue by praveenshharma** [noties/Scrollable#58]
I have a listview below a viewpager and in the initial state (when nothing has been scrolled), the  viewpager shows only one item with a 10dp "preview" of the next and previous items (I have achieved this by setting a negative page margin:viewPager.setPageMargin(-48);). What I am trying to do is, on scrolling down the listview
1) the listview should "push" the viewpager up, decreasing its height up to a certain point. On reaching that point (some minHeight for the viewpager), the listview should scroll normally with the smaller sized viewpager above it.

2) The next and the previous items in the viewpager should pull inside (towards the central item) and in the final state, three items of the viewpager should be fully displayed. (Images below to illustrate this)

Scrolling up the listview should do the opposite.

Initial state (nothing scrolled)

![first](https://user-images.githubusercontent.com/15669246/34037255-14fc1c22-e1ae-11e7-8c30-8ff9745ac9d9.jpg)

Final state (minHeight of viewpager to be achieved)

![second](https://user-images.githubusercontent.com/15669246/34037273-28b6e5d0-e1ae-11e7-8fe6-f60e625dc57a.jpg)

I'm not able to do with Scrollable, Can anyone help me achieve this ?

**Comment by noties** [comment]
Hello!

I think that that you want to achieve is really doable with ScrollableLayout. You scroll, receive scroll ratio, apply new width and height to the views in header. Sounds simple. But...

The thing is `ViewPager` is not really a suitable choice for the functionality you are planning to implement. It _could_ be if we could dynamically change the `page_width` attribute, forcing all layed-out views to be invalidated. But unfortunately there is no such opportunity. (I'm not talking about height because it's relatively simple).

There is also ability to mimic ViewPager functionality with `RecyclerView` and PagerSnapHelper. But... it won't work if views are **not** `match_parent`. On the other hand, if _snapping_ is not required, we could've used just RecyclerView with horizontal `LinearLayoutManager`. But... quick look showed, that it is also not designed for dynamic width of items.

To sum up, as far as I know there is no such widget that would answer your needs. But if doesn't mean that it cannot be created.

Most likely all widgets that recycle attached views are not suitable (so, RecyclerView, ListView, GridLayout, etc are out). As we would require all Views to be in layout at any moment of width/height modification. 

**If** you have finite number of header items, you could use `HorizontalScrollView`. Let's consider this:

```java
public class PagerScrollView extends HorizontalScrollView {
    
    // code will be introduced further
    private PagerLinearLayout pagerLinearLayout;

    private float pageWidthRatio;
    private int pageHeight;
    
    /** constructors are omitted **/

    public void setPageDimensions(float pageWidthRatio, int pageHeight) {
        this.pageWidthRatio = pageWidthRatio;
        this.pageHeight = pageHeight;
        requestLayout();
    }
    
    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();

        this.pagerLinearLayout = (PagerLinearLayout) getChildAt(0);
    }
    
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        
        if (pageWidthRatio > 0
                && pageHeight > 0) {
            
            final int width = MeasureSpec.getSize(widthMeasureSpec);
            
            pagerLinearLayout.setDimensions(
                    (int) (pageWidthRatio * width + .5F),
                    pageHeight
            );   
        }
        
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }
}
```

```java
public class PagerLinearLayout extends LinearLayout {

    private int pageWidth;
    private int pageHeight;

    /** constructors are omitted **/

    public void setDimensions(int pageWidth, int pagerHeight) {
        this.pageWidth = pageWidth;
        this.pageHeight = pagerHeight;
        requestLayout();
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {

        if (pageHeight > 0) {
            heightMeasureSpec = MeasureSpec.makeMeasureSpec(pageHeight, MeasureSpec.EXACTLY);
        }

        if (pageWidth > 0) {
            final int count = getChildCount();
            View view;
            for (int i = 0; i < count; i++) {
                view = getChildAt(i);
                view.getLayoutParams().width = pageWidth;
            }
        }

        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }
}
```

Now, we have a horizontally scrollable view with ability to manipulate width and height dynamically. `PagerLinearLayout` can be populated in XML layout or in runtime. I would look up some LinearLayout adapter implementation for more reusable behaviour.

```xml
<?xml version="1.0" encoding="utf-8"?>
<ru.noties.scrollable.ScrollableLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/scrollable_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:scrollable_defaultCloseUp="true">

    <ru.noties.scrollable.sample.pg.PagerScrollView
        android:id="@+id/pager_scroll_view"
        android:layout_width="match_parent"
        android:layout_height="@dimen/pager_height_max"
        android:clipChildren="false"
        android:clipToPadding="false"
        android:padding="4dip">

        <ru.noties.scrollable.sample.pg.PagerLinearLayout
            android:id="@+id/pager_linear_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="bottom" />

    </ru.noties.scrollable.sample.pg.PagerScrollView>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</ru.noties.scrollable.ScrollableLayout>
```

```java
public class MainActivity extends Activity {

    private static final float PAGE_WIDTH_MAX = .75F;
    private static final float PAGE_WIDTH_MIN = .30F;
    
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // our height resources (for example, 200dip & 100dip)
        final int maxHeight;
        final int minHeight;
        final int maxScroll;
        {
            final Resources r = getResources();
            maxHeight = r.getDimensionPixelSize(R.dimen.pager_height_max);
            minHeight = r.getDimensionPixelSize(R.dimen.pager_height_min);
            
            // difference between the two (will be the maxScroll argument)
            maxScroll = maxHeight - minHeight;
        }

        final ScrollableLayout scrollableLayout = findViewById(R.id.scrollable_layout);
        final PagerScrollView pagerScrollView = findViewById(R.id.pager_scroll_view);

        scrollableLayout.setMaxScrollY(maxScroll);
        
        scrollableLayout.addOnScrollChangedListener(new OnScrollChangedListener() {

            final float pageWidthDiff = PAGE_WIDTH_MAX - PAGE_WIDTH_MIN;

            @Override
            public void onScrollChanged(int y, int oldY, int maxY) {

                final float ratio = 1.F - ((float) y / maxY);

                final float pageWidth = PAGE_WIDTH_MIN + (ratio * pageWidthDiff);
                final int pageHeight = (int) (maxScroll + (ratio * maxScroll) + .5F);
                pagerScrollView.setPageDimensions(pageWidth, pageHeight);
            }
        });
        
        // do not forget to set initial values
        pagerScrollView.setPageDimensions(PAGE_WIDTH_MAX, maxHeight);
    }
}
```

So, using this I have achieved this behaviour:
![output](https://user-images.githubusercontent.com/7278986/34049098-33d330cc-e1c7-11e7-8f52-19b86d748a34.gif)

But, as it's not complete: 
![output](https://user-images.githubusercontent.com/7278986/34049136-51e56c24-e1c7-11e7-9489-cb0914102372.gif)

Please note, that it's just a direction that I see. This implementation still lacks _snapping_ (whilst dragging horizontally) and keeping the scroll position on width/height change (keep focus on a view). But could be a good start if you decide to go with custom implementation of header widget.

Hope this helps!
Dimitry

**Comment by praveenshharma** [comment]
@noties Thanks for your reply, from your result ITEM0 ITEM1 ITEM2 are the main previews, but when you scrolls the list towards Recycler View ITEM1 goes to previous position and ITEM2 ITEM3 ITEM4 are showing at last. Can you just tell me how can we solve out ? because I just want to scale it from both sides, Middle view goes straight and left and right view should come from left and right sides with scaling and translation.
2) Why can't I use View Pager like If I create a view pager of 1000dp approx and keep in Header View just apply Scale and Translation and show these 3 items ?
3) I want to use Fast Velocity Based Scrolling so I was thinking to use Velocity based View Pager
4) Recycler View won't allow to scroll mid view at stationary point i think.

**Comment by praveenshharma** [comment]
@noties Is this possible?

**Comment by noties** [comment]
@mobilegeekkk Most likely. Can you show me what have you tried already?

**Comment by praveenshharma** [comment]
@noties As i told you that I had created this view with Velocity ViewPager ( Acceleration based ViewPager) containing reference width 1000dp and at runtime I calculated it for 3 items. I had used ParallaxHeaderViewPager library [https://github.com/carlonzo/StikkyHeader](url) for this. So when this library scales its headerView, I scales ViewPager width so it can fit it in Rect with 3 items. All things were achieved but there was an problem with scaling in this library or I was missing something. I tried a lot with this but on some devices scaling was not accurate.
